name: First Practical Workflow

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions "

      - name: Show date
        run: date

      - name: Show current directory
        run: pwd

      - name: Listing the files
        run: ls -la

      - name: Force Failure
        run:  exit 1

      - name: Run only on failure
        if: failure()
        run: echo "This runs because of job is failed"

      - name: Run only on success
        if: success()
        run: echo "This runs because the job is succeed"

      - name: Run always
        run: echo "This is a last Message Commited Changes"
      
        
        
