name: First Practical Workflow

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions "

      - name: Show date
        run: date

      - name: Show current directory
        run: pwd

      - name: Listing the files
        run: ls -la

      - name: Force Failur
        run: |
         echo "This step will failure"
         exit 1
